version: "3.7"

services:
  shoyu-test-redis:
    image: redis:alpine
    container_name: shoyu-test-redis
    environment:
      - REDIS_REPLICATION_MODE=master
    networks:
      - shoyu-test
    ports:
      - "6379:6379"
    volumes:
      - "shoyu-test-redis:/var/lib/redis"
      - "shoyu-test-redis:/usr/local/etc/redis/redis.conf"
    restart: unless-stopped

  shoyu-redis-web:
    image: rediscommander/redis-commander:latest
    container_name: shoyu-test-redis-web
    environment:
      - REDIS_HOSTS=local:shoyu-test-redis:6379
    networks:
      - shoyu-test
    ports:
      - "9060:8081"
    depends_on:
      - shoyu-test-redis
    restart: unless-stopped

  shoyu-test-mongo:
    image: mongo:latest
    container_name: shoyu-test-mongo
    environment:
      - MONGO_INITDB_DATABASE=app
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=password
    networks:
      - shoyu-test
    ports:
      - "27017:27017"
    volumes:
      - "shoyu-test-mongo:/data/db:delegated"
    restart: unless-stopped

  shoyu-test-mongo-web:
    image: mongo-express:latest
    container_name: shoyu-test-mongo-web
    environment:
      - ME_CONFIG_MONGODB_SERVER=shoyu-test-mongo
      - ME_CONFIG_MONGODB_ADMINUSERNAME=mongo
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
    networks:
      - shoyu-test
    ports:
      - "9070:8081"
    depends_on:
      - shoyu-test-mongo
    restart: unless-stopped

#  shoyu-test-server:
#    build:
#      context: .
#    container_name: shoyu-test-server
#    env_file: .env
#    networks:
#      - shoyu-test
#    ports:
#      - "9080:9080"
#    volumes:
#      - "./src:/app/shoyu-test/src:cached"
#    depends_on:
#      - shoyu-test-redis
#      - shoyu-test-mongo
#    restart: unless-stopped

volumes:
  shoyu-test-mongo:
  shoyu-test-redis:

networks:
  shoyu-test:
